# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DJBHOSTING - Managed and Dedicated Web Hosting 
email: contact@djbhosting.co.uk
description: Need a Website? DJBHosting can get you up and running in to time and with no hassle. You focus on your content - DJBHosting will focus on setting the site up and installing any plugins, themes and features you require.

keywords: Wordpress, webhosting, jekyll, vuepress, hugo, hosting, djbhosting, managed, VPS, dedicated, server, servers, database, support, technical, datacenter 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://djbhosting.danbennett.me" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  danbennettuk
google_analytics_tracking_id: UA-141510027-1 
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
incremental: true
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - 404.html

include: ['.htaccess']
